### ISSUE TITLE
Are there any plans to have a javascript version of this library?

### ISSUE THREAD

**Issue by douglascvas** [mpollmeier/orientdb-gremlin#159]
I wonder if there will be a version of this library in javascript.
I am currently trying to access orientdb through the gremlin javascript library, but it has some problems:
- Ids returned from addV operations are temporary
- Does not support transactions

Database version: OrientDB 3.0.14

**Comment by wolf4ood** [comment]
Hi @douglascvas 

the official JS driver is OrientJS which uses OrientDB binary protocol. It can be used to spawn gremlin queries over the OrientDB binary protocol if the distribution is OrientDB with Apache Tinkerpop3. But i would recommend to use the gremlin javascript driver since it's support gremlin traversal with GLV, which i guess is something you want. and gives you the abstraction over the underlying graph technology.
If you do not care about abstraction you might as well use OrientJS with SQL.

For the problem the temporary ids are a known issue with the integration of this driver inside the gremlin server due transaction lifecycle.

For transaction do you mean transactions over multiple requests?

Thanks
Enrico

**Comment by wolf4ood** [comment]
Hi @douglascvas 

do you need other info on this?

Thanks
