### ISSUE TITLE
Run sbt tests on travis

### ISSUE THREAD

**Issue by velo** [mpollmeier/orientdb-gremlin#25]
We do need to enable sbt test on travis CI.

**Comment by mpollmeier** [comment]
hmm, for maven you just specify `mvn -f path/to/pom.xml` but I don't know how you can do that for sbt: http://www.scala-sbt.org/0.13/docs/Command-Line-Reference.html

This mix of technologies and isn't really nice, the orientdb-driver should not depend on gremlin-scala (it doesn't, only the tests do, but still). I only started that way because I couldn't be bothered with java :P 
A better place would be the https://github.com/mpollmeier/gremlin-scala-examples - should I move them there?

**Comment by velo** [comment]
Well, if this is a set of tests, we should keep them here.... if not, there is no need to add to the build and we can keep them.

**Comment by velo** [comment]
Done in https://github.com/mpollmeier/orientdb-gremlin/commit/9339f604425fb03e7aa80a59ca2b906d38d0c223
